# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

copyright("© #{Time.now.year} Your Company)

price_tier(0)

skip_screenshots(true)
skip_metadata(false)
force(true) #skips html verification
submit_for_review(false)
automatic_release(false)
app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: true
})